networks:
  kafka_production_network:
    driver: bridge
  kafka_analytics_network:
    driver: bridge
  kontext_network:
    driver: bridge
volumes:
  kafka-production-0: null
  kafka-analytics-0: null

services:
  api:
    build:
      context: ./apps/api
    env_file:
      - .env
    ports:
      - "${API_PORT:-4000}:${API_PORT:-4000}"
    networks:
      - kafka_production_network
      - kafka_analytics_network
      - kontext_network

  web:
    build:
      context: ./apps/web
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-3000}:${WEB_PORT:-3000}"
    networks:
      - kontext_network

  # PRODUCTION Kafka Cluster
  kafka-production-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://kafka-production-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://kafka-production-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr kafka-production-0:33145
      - --advertise-rpc-addr kafka-production-0:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
    container_name: kafka-production-0
    volumes:
      - kafka-production-0:/var/lib/redpanda/data
    networks:
      - kafka_production_network
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644

  # ANALYTICS Kafka Cluster
  kafka-analytics-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:29092
      - --advertise-kafka-addr internal://kafka-analytics-0:9092,external://localhost:29092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:28082
      - --advertise-pandaproxy-addr internal://kafka-analytics-0:8082,external://localhost:28082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:28081
      - --rpc-addr kafka-analytics-0:33146
      - --advertise-rpc-addr kafka-analytics-0:33146
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
    container_name: kafka-analytics-0
    volumes:
      - kafka-analytics-0:/var/lib/redpanda/data
    networks:
      - kafka_analytics_network
    ports:
      - 28081:28081
      - 28082:28082
      - 29092:29092
      - 29644:9644

  # PRODUCTION Console
  console-production:
    container_name: redpanda-console-production
    image: docker.redpanda.com/redpandadata/console:v3.1.2
    networks:
      - kafka_production_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka-production-0:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://kafka-production-0:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://kafka-production-0:9644"]
    ports:
      - 8080:8080
    depends_on:
      - kafka-production-0

  # ANALYTICS Console
  console-analytics:
    container_name: redpanda-console-analytics
    image: docker.redpanda.com/redpandadata/console:v3.1.2
    networks:
      - kafka_analytics_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka-analytics-0:9092"]
        schemaRegistry:
          enabled: true
          urls: ["http://kafka-analytics-0:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://kafka-analytics-0:9644"]
    ports:
      - 8081:8080
    depends_on:
      - kafka-analytics-0
