networks:
  kafka_production_network:
    driver: bridge
  kafka_analytics_network:
    driver: bridge
volumes:
  kafka-production-0: null
  kafka-analytics-0: null

services:
  api:
    build:
      context: ./apps/api
    env_file:
      - .env
    ports:
      - "${API_PORT:-4000}:${API_PORT:-4000}"
    networks:
      - kafka_production_network
      - kafka_analytics_network

  web:
    build:
      context: ./apps/web
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-3000}:${WEB_PORT:-3000}"

  # PRODUCTION Kafka Cluster
  kafka-production-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092
      - --advertise-kafka-addr internal://kafka-production-0:9092
      - --rpc-addr kafka-production-0:33145
      - --advertise-rpc-addr kafka-production-0:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
    container_name: kafka-production-0
    volumes:
      - kafka-production-0:/var/lib/kafka/data
    networks:
      - kafka_production_network

  # ANALYTICS Kafka Cluster
  kafka-analytics-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092
      - --advertise-kafka-addr internal://kafka-analytics-0:9092
      - --rpc-addr kafka-analytics-0:33146
      - --advertise-rpc-addr kafka-analytics-0:33146
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
    container_name: kafka-analytics-0
    volumes:
      - kafka-analytics-0:/var/lib/kafka/data
    networks:
      - kafka_analytics_network
