services:
  api:
    build:
      context: ./apps/api
    env_file:
      - .env
    ports:
      - "${API_PORT:-4000}:${API_PORT:-4000}"

  web:
    build:
      context: ./apps/web
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-3000}:${WEB_PORT:-3000}"

