# Redpanda Dockerfile template from https://docs.redpanda.com/redpanda-labs/docker-compose/single-broker/
networks:
  kafka_rides_network:
    driver: bridge
  kafka_users_network:
    driver: bridge
  kafka_drivers_network:
    driver: bridge
  kafka_payments_network:
    driver: bridge
  kontext_network:
    driver: bridge
volumes:
  kafka-rides-0: null
  kafka-users-0: null
  kafka-drivers-0: null
  kafka-payments-0: null

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT:-3001}:${API_PORT:-3001}"
    networks:
      - kafka_rides_network
      - kafka_drivers_network
      - kafka_users_network
      - kafka_payments_network
      - kontext_network

  glide:
    build:
      context: .
      dockerfile: glide/Dockerfile
    env_file:
      - .env
    # ports:
    #   - "5000:5000"
    networks:
      - kafka_rides_network
      - kafka_drivers_network
      - kafka_users_network
      - kafka_payments_network
      - kontext_network


  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-3000}:${WEB_PORT:-3000}"
    networks:
      - kontext_network

  # RIDES Kafka Cluster
  kafka-rides-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://kafka-rides-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://kafka-rides-0:8082,external://localhost:18082
      - --rpc-addr kafka-rides-0:33145
      - --advertise-rpc-addr kafka-rides-0:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
    container_name: kafka-rides-0
    volumes:
      - kafka-rides-0:/var/lib/redpanda/data
    networks:
      - kafka_rides_network
    ports:
      - 18082:18082
      - 19092:19092
      - 19644:9644


  # USERS Kafka Cluster
  kafka-users-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:29092
      - --advertise-kafka-addr internal://kafka-users-0:9092,external://localhost:29092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:28082
      - --advertise-pandaproxy-addr internal://kafka-users-0:8082,external://localhost:28082
      - --rpc-addr kafka-users-0:33146
      - --advertise-rpc-addr kafka-users-0:33146
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
    container_name: kafka-users-0
    volumes:
      - kafka-users-0:/var/lib/redpanda/data
    networks:
      - kafka_users_network
    ports:
      - 28082:28082
      - 29092:29092
      - 29644:9644

  # DRIVERS Kafka Cluster
  kafka-drivers-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:39092
      - --advertise-kafka-addr internal://kafka-drivers-0:9092,external://localhost:39092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:38082
      - --advertise-pandaproxy-addr internal://kafka-drivers-0:8082,external://localhost:38082
      - --rpc-addr kafka-drivers-0:33145
      - --advertise-rpc-addr kafka-drivers-0:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
    container_name: kafka-drivers-0
    volumes:
      - kafka-drivers-0:/var/lib/redpanda/data
    networks:
      - kafka_drivers_network
    ports:
      - 38082:38082
      - 39092:39092
      - 39644:9644

  # PAYMENTS Kafka Cluster
  kafka-payments-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:49092
      - --advertise-kafka-addr internal://kafka-payments-0:9092,external://localhost:49092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:48082
      - --advertise-pandaproxy-addr internal://kafka-payments-0:8082,external://localhost:48082
      - --rpc-addr kafka-payments-0:33145
      - --advertise-rpc-addr kafka-payments-0:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v25.1.5
    container_name: kafka-payments-0
    volumes:
      - kafka-payments-0:/var/lib/redpanda/data
    networks:
      - kafka_payments_network
    ports:
      - 48082:48082
      - 49092:49092
      - 49644:9644

  # RIDES Console
  console-rides:
    container_name: redpanda-console-rides
    image: docker.redpanda.com/redpandadata/console:v3.1.2
    networks:
      - kafka_rides_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka-rides-0:9092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://kafka-rides-0:9644"]
    ports:
      - 8080:8080
    depends_on:
      - kafka-rides-0

  # USERS Console
  console-users:
    container_name: redpanda-console-users
    image: docker.redpanda.com/redpandadata/console:v3.1.2
    networks:
      - kafka_users_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka-users-0:9092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://kafka-users-0:9644"]
    ports:
      - 8081:8080
    depends_on:
      - kafka-users-0


  # DRIVERS Console
  console-drivers:
    container_name: redpanda-console-drivers
    image: docker.redpanda.com/redpandadata/console:v3.1.2
    networks:
      - kafka_drivers_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka-drivers-0:9092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://kafka-drivers-0:9644"]
    ports:
      - 8082:8080
    depends_on:
      - kafka-drivers-0


  # PAYMENTS Console
  console-payments:
    container_name: redpanda-console-payments
    image: docker.redpanda.com/redpandadata/console:v3.1.2
    networks:
      - kafka_payments_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka-payments-0:9092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://kafka-payments-0:9644"]
    ports:
      - 8083:8080
    depends_on:
      - kafka-payments-0
