# From https://github.com/conduktor/kafka-stack-docker-compose
# Updated to use KRaft mode (no ZooKeeper required)
services:
  rides:
    image: confluentinc/cp-kafka:7.8.0
    hostname: rides
    container_name: rides
    ports:
      - "9092:9092"
      - "19092:19092"
      - "39092:39092"
      - "9992:9992"
    environment:
      # KRaft mode configuration - RIDES CLUSTER
      CLUSTER_ID: 'rides-cluster'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@rides:19092'
      KAFKA_LISTENERS: PLAINTEXT://rides:9092,CONTROLLER://rides:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:39092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://rides:9092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9992
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

  users:
    image: confluentinc/cp-kafka:7.8.0
    hostname: users
    container_name: users
    ports:
      - "9093:9093"
      - "19093:19093"
      - "39093:39093"
      - "9993:9993"
    environment:
      # KRaft mode configuration - USERS CLUSTER
      CLUSTER_ID: 'users-cluster'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@users:19093'
      KAFKA_LISTENERS: PLAINTEXT://users:9093,CONTROLLER://users:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:39093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://users:9093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:39093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9993
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

  drivers:
    image: confluentinc/cp-kafka:7.8.0
    hostname: drivers
    container_name: drivers
    ports:
      - "9094:9094"
      - "19094:19094"
      - "39094:39094"
      - "9994:9994"
    environment:
      # KRaft mode configuration - DRIVERS CLUSTER
      CLUSTER_ID: 'drivers-cluster'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@drivers:19094'
      KAFKA_LISTENERS: PLAINTEXT://drivers:9094,CONTROLLER://drivers:19094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:39094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://drivers:9094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:39094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9994
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"

  payments:
    image: confluentinc/cp-kafka:7.8.0
    hostname: payments
    container_name: payments
    ports:
      - "9095:9095"
      - "19095:19095"
      - "39095:39095"
      - "9995:9995"
    environment:
      # KRaft mode configuration - PAYMENTS CLUSTER
      CLUSTER_ID: 'payments-cluster'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@payments:19095'
      KAFKA_LISTENERS: PLAINTEXT://payments:9095,CONTROLLER://payments:19095,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:39095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://payments:9095,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:39095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9995
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"


