name: Web Linting and Formatting

on:
  push:
    branches: [main]
    paths:
      - "services/web/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
    paths:
      - "services/web/**"

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml

  lint-web:
    if: github.event.pull_request.draft == false
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run linting and formatting
        working-directory: ./services/web
        run: npm run clean
